### PR TITLE
Remove all non-Deploy content

### PR DESCRIPTION
**Pull request by fancyremarker**
This attempts to remove all non-Deploy content from individual pages and navs.

In the process of this PR, I was also able to identify a list of all the changes I think we should consider making before pushing this live, in priority order:

**P1**
* [ ] @neurosnap Ensure everything works against production Contentful (with resources removed and 
* [ ] @fancyremarker Review/edit/publish the Aptible/Conveyor blog post and replace the HelloBar to announce it
* [ ] Support all redirects defined either in `_redirects` in www or in Webflow, reconciling any discrepancies
* [ ] Update all signup buttons (to go directly to dashboard.aptible.com)
* [ ] @fancyremarker Update the copy on the homepage and /features
* [ ] Support /404 as custom 404 page (instead of NGiNX default)

**P2**
* [ ] Unpublish/archive Comply posts and webinars in Contentful
* [ ] @fancyremarker Add final changelog post announcing move to Readme changelog
* [ ] Backport new, relevant (Deploy or culture) blog posts into Contentful
* [ ] Add new team members to Contentful and archive Conveyor team members. Everyone seems to be on https://www.aptible.com/company/about , so this should be just a matter of copy/pasting into Contentful.
* [ ] Switch Readme DNS from deploy-docs.aptible.com to docs.aptible.com, and update links in the website
* [ ] Configure NGiNX to return 404 instead of 403 (e.g. on /get/)
* [ ] Add a Webinar category to the Blog to filter to webinars

### CODE REVIEW

**Comment by neurosnap** [comment]
When running `yarn develop` I got the error:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                             10:06:54 AM

 error  in ./src/templates/webinar.js

Module Error (from ./node_modules/eslint-loader/index.js):

/Users/ericbower/work/www/src/templates/webinar.js
  30:7  error  Cannot query field "presenter1" on type "ContentfulWebinar". Did you mean "presenter2"?  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


 @ ./.cache/sync-requires.js 21:60-121
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

✖ ｢wdm｣:
ERROR in ./src/templates/webinar.js
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/ericbower/work/www/src/templates/webinar.js
  30:7  error  Cannot query field "presenter1" on type "ContentfulWebinar". Did you mean "presenter2"?  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)

 @ ./.cache/sync-requires.js 21:60-121
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.
```

**Comment by neurosnap** [comment]
It looks like this bug happens on master as well.

**Comment by neurosnap** [comment]
http://localhost:8001/press/

Screen Shot 2021-06-23 at 10 31 20 AM

**Comment by neurosnap** [comment]
http://localhost:8001/blog/category/engineering/

Screen Shot 2021-06-23 at 10 33 49 AM

**Comment by neurosnap** [comment]
In the footer have a "Contact support" link that directs people to a mostly blank page

Screen Shot 2021-06-23 at 10 35 07 AM

**Review by almathew — APPROVED** [review]

**Comment by fancyremarker** [comment]
@neurosnap:

> In the footer have a "Contact support" link that directs people to a mostly blank page

Good call. This is actually also the case on the live aptible.com. I pushed a fix for that.

> http://localhost:8001/press/

Good call also. Removed the Employees count.

For your other comments, as discussed, there is more involved with getting this to work on production Contentful, and you're tackling that separately. I added that as a P1 TODO.

**Pull request merged**
